export const SET_LOADING = 'SET_LOADING';

// Registration and Login
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

// Editions
export const ADD_EDITION_SUCCESS = 'ADD_EDITION_SUCCESS';
export const ADD_EDITION_FAILURE = 'ADD_EDITION_FAILURE';
export const GET_EDITION_SUCCESS = 'GET_EDITION_SUCCESS';
export const GET_EDITION_FAILURE = 'GET_EDITION_FAILURE';
export const GET_EDITIONS_SUCCESS = 'GET_EDITIONS_SUCCESS';
export const GET_EDITIONS_FAILURE = 'GET_EDITIONS_FAILURE';

// Artists
export const GET_ARTISTS_FAILURE = 'GET_ARTISTS_FAILURE';
export const GET_ARTISTS_SUCCESS = 'GET_ARTISTS_SUCCESS';

// NewsPosts
export const GET_NEWSPOST_SUCCESS = 'GET_NEWSPOST_SUCCESS';
export const GET_NEWSPOST_FAILURE = 'GET_NEWSPOST_FAILURE';
export const GET_NEWSPOSTS_SUCCESS = 'GET_NEWSPOSTS_SUCCESS';
export const GET_NEWSPOSTS_FAILURE = 'GET_NEWSPOSTS_FAILURE';
export const ADD_NEWSPOST_SUCCESS = 'ADD_NEWSPOST_SUCCESS';
export const ADD_NEWSPOST_FAILURE = 'ADD_NEWSPOST_FAILURE';
