export const SET_LOADING = 'SET_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const ADD_EDITION_SUCCESS = 'ADD_EDITION_SUCCESS';
export const ADD_EDITION_FAILURE = 'ADD_EDITION_FAILURE';
export const GET_EDITION_SUCCESS = 'GET_EDITION_SUCCESS';
export const GET_EDITION_FAILURE = 'GET_EDITION_FAILURE';
export const GET_EDITIONS_SUCCESS = 'GET_EDITIONS_SUCCESS';
export const GET_EDITIONS_FAILURE = 'GET_EDITIONS_FAILURE';
